### PR TITLE
Add CLANG_CXX_LANGUAGE_STANDARD and requires_arc to the CocoaPods specs.

### PR DESCRIPTION
**Pull request by rhcad**
Other suggestions:

``` ruby
s.version     = '1.2.0-alpha'
```

### CODE REVIEW

**Comment by adamgit** [comment]
As far as I'm aware, this still runs on iOS 4.

c.f. the other threads, the consensus was that we'd bump the version number before we increase the requries iOS version (and probably switch to ARC at the same time?)

**Comment by rhcad** [comment]
iOS 4 and SVGKit version can remain unchanged, but I think `gnu++11` and non-ARC should be specified.

**Comment by adamgit** [comment]
OK, sounds good. I can't edit the commit, sorry - you'll have to resubmit.

I think we should move to new version very soon! :)

**Comment by rhcad** [comment]
Moved to #169 .

**Pull request closed without merging**
