### PR TITLE
Enhancements and bug fixes

### PR DESCRIPTION
**Pull request by mindbrix**
Support for floating point coordinates. Support for relative path
coordinates. Parser bug fixes and improvements. Added more examples to
test the renderer.

### CODE REVIEW

**Comment by steipete** [comment]
You really shouldn't checkin the *.mode1v3 and *.pbxuser - makes the commit way larger than it should be.

**Comment by mindbrix** [comment]
Good point. Is there any way to trim the commit. I'm still learning Git after years of SVN.

**Comment by steipete** [comment]
Uhh... best way would be to rewrite history, to purge the files completely, It's a bit tricky, google has some good answers on this. And add a .gitignore, it's really the repository master's fault ;) (and then re-open another request)

**Comment by jwang** [comment]
Look at [GitHub crowd-sourced gitignore repo](github.com/github/gitignore). It's got an Objective-C one, core OS ones for mac and more.

**Comment by mindbrix** [comment]
Thanks. The Objective-C .gitignore doesn't seem to play nicely with Github for Mac yet.

**Comment by reklis** [comment]
just pull into a branch and pull out whatever you want with git diff into a patch file, then apply the patch to whatever other branch directly.

**Comment by adamgit** [comment]
FYI I'm planning to CLOSE this request WITHOUT MERGING.

I want to overwrite the main repository with the reklis fork - there are over 1,000 new lines, and 500 changed, since the last update to master. I _believe_ all the changes in this pull request now exist in the reklis fork - either merged in, or have been reproduced by someone else?

If so - no work needed, they're already in place, and will be included automatically.

If not - please could you try re-applying your changes to the reklis fork, and see if it works OK?

Thanks!

**Comment by mindbrix** [comment]
Fine by me. Good luck with the merge. You're doing some great work.

**Pull request closed without merging**
