### PR TITLE
fix memory leak of NSDates

### PR DESCRIPTION
**Pull request by dpletter**
Loading any svg file into a SVGKFastImageView shows leaks of 2 NSDate objects from SVGKFastImageView when leak profiling in Instruments.  This change resolves those leaks.

### CODE REVIEW

**Comment by adamgit** [comment]
Please can you re-apply this to the current branch?

Use the front page, or point your git client at branch "2.x"

**Comment by dpletter** [comment]
Ok, but should the readme be updated?

"
v1.x = current "in development" branch with latest changes, fixes, features
NB: this is now automatically selected in GitHub as the "default" branch when you visit SVGKit's project page
USE THIS FOR EVERYTHING UNLESS YOU HAVE A VERY GOOD REASON NOT TO!
"

**Comment by adamgit** [comment]
Yes, it's wrong!

**Comment by adamgit** [comment]
Closing because this is now applied to 2.x, and the README was fixed in https://github.com/SVGKit/SVGKit/commit/cd47ae95e57c9490a9238173855ecbe83d4aaf44

**Pull request closed without merging**
