### PR TITLE
removing cocoalumberjack dependecy from latest version

### PR DESCRIPTION
**Pull request by lagubull**
WE WON't MERGE this, it is only for visibility of the changes

### CODE REVIEW

**Comment by danieltmbr** [comment]
Why don't we merge? what's the purpose of the PR then?
Also why do we need to remove CocoaLumberjack?

**Comment by lagubull** [comment]
I don't want to merge it so that we can keep 3.x free of any TW changes so we can simply fetch from upstream whenever we need to.

**Comment by lagubull** [comment]
cocoaLumberJack is used in other pods and that causes issues according to XCode warnings...

**Comment by adamgit** [comment]
I also don't understand the point of this, it would be great if you could
give a slightly more detailed description.

AFAICS:
 1. This unlinks Lumberjack
 2. This removes Lumberjack from Cocoapods
 3. The purpose is ... ?? to workaround a bug in Cocoapods ??

If Cocoapods is preventing you from managing LJ versions easily and in
*compatible, non-proprietary* ways, that sounds like a huge bug in CP. Is
that the case?

I know it happened in the past (it's one of the reasons we banned CP from
projects at multiple companies I worked at), but I thought they fixed those
bugs long ago? Surely CP has this covered by now?

**Comment by lagubull** [comment]
Sorry, this PR was meant to go to my internal 3.x branch. not public

**Comment by adamgit** [comment]
Ah! LOL OK, no worries :).

**Pull request closed without merging**
