### PR TITLE
iPhone 5s has the same density as 5 and 4

### PR DESCRIPTION
**Pull request by rrbrambley**
The iPhone 5s (hw.machine values of iPhone6,1 and iPhone6,2) has the same pixel density as the iPhone 5.
This fixes issue #106.

### CODE REVIEW

**Comment by bdalziel** [comment]
I haven't checked, but is iPhone6 the identifier for the 5C and 5S? I don't know either way, but i just submitted this before i noticed yours:

https://github.com/SVGKit/SVGKit/pull/112

**Comment by bdalziel** [comment]
It must be, ignore me - thanks for posting the correct pull request.

**Comment by cbhl** [comment]
@bdalziel: AFAICT, the iPhone 5C still returns a string starting with "iPhone5", but the iPhone 5S returns a string starting with "iPhone6". (Perhaps due to things like having a 64-bit processor?)

**Comment by adamgit** [comment]
Ah, nicely caught!

Can you re-submit this against 1.x branch?

(I've fixed github so it always defaults to this branch now, correctly, as the active commit branch for development)

Sorry - I can't seem to get github to let me re base it automatically :(

**Pull request closed without merging**
