### PR TITLE
Made project build for all architectures (include arm64) and memory issues

### PR DESCRIPTION
**Pull request by cjhanson**
Made project build for all architectures (include arm64)
Fixed some memory leaks that the clang analyzer pointed out

### CODE REVIEW

**Comment by adamgit** [comment]
Quick check: We had some problems in Xcode 5.0.0 where it didn't correctly link libraries which had 64bit code - have you re-built the library from clean, and checked you can import it into an app (e.g. the demo app) and the app runs correctly?

(from (vague!) memory: Xcode 5.0.0 was dropping a slice when it output the .a file, and so you ended up with a library that was missing 386 or similar - i.e. wouldn't run on simulator, or wouldn't run on non-64bit devices ... something silly like that)

**Comment by adamgit** [comment]
NB: I found a few that were missing after this, and just did another commit that added them. I think we've got the lot now (I did a Clean to check)

**Comment by cjhanson** [comment]
Great thanks :) This project is super helpful.

**Comment by adamgit** [comment]
Then comment here: https://github.com/SVGKit/SVGKit/issues/140

(I want to find out what people are using it for, and compile some screenshots + testimonials in the new year)

**Comment by cjhanson** [comment]
I will certainly do that as soon as my app is on the store :)

**Pull request merged**
