### PR TITLE
Add Swift Package Manager support

### PR DESCRIPTION
**Pull request by karimhm**
This commit do the following:

- Add explicit import declarations.
- Add more conditionals to handle multi platform
- Import `SVGKDefine_Private.h` (prefix headers do not work in Swift PM mode).

### CODE REVIEW

**Comment by adamgit** [comment]
If we can't use the PCH file, we should get rid of it entirely - otherwise future developers are likely to add things to it.

As far as I can tell, SwiftPM refuses to support PCH?

**Comment by karimhm** [comment]
> If we can't use the PCH file, we should get rid of it entirely - otherwise future developers are likely to add things to it.
> 
> As far as I can tell, SwiftPM refuses to support PCH?

In Xcode based projects, you go to `Build Settings` -> `Prefix Header` to specify the prefix header, but from Swift Package Manager based projects there is no way to specify that.

All the internal definitions and flags that were inside the prefix header have been moved to `SVGKDefine_Private.h`.

**Comment by satindar** [comment]
@karimhm @adamgit Just tried to install the `3.x` branch via Cocoapods and am running into this error:

`Errno::ENOENT - No such file or directory @ rb_sysopen - /Pods/SVGKit/SVGKitLibrary/SVGKit-iOS/SVGKit-Prefix.pch`

So looks like there's some more config needed to support both SPM and Cocoapods.

**Comment by karimhm** [comment]
@satindar @adamgit The following line need to be removed
https://github.com/SVGKit/SVGKit/blob/3.x/SVGKit.podspec#L26

**Comment by karimhm** [comment]
@satindar I believe the issue was fixed.
Can you try **SVG 2.2.0** from the following specs repo: https://github.com/karimhm/SVGKit-Specs.git

**Comment by karimhm** [comment]
@adamgit Swift Package Manager work best with git tags so a new tag need to be added such as **3.0.0** to allow the use of SVGKit as a swift package.

**Comment by bangjier** [comment]
> @karimhm @adamgit Just tried to install the `3.x` branch via Cocoapods and am running into this error:
> 
> `Errno::ENOENT - No such file or directory @ rb_sysopen - /Pods/SVGKit/SVGKitLibrary/SVGKit-iOS/SVGKit-Prefix.pch`
> 
> So looks like there's some more config needed to support both SPM and Cocoapods.

Me too. How did you solve it

**Comment by karimhm** [comment]
@bangjier #683 should fix it

**Comment by bangjier** [comment]
> @bangjier [＃683](https://github.com/SVGKit/SVGKit/pull/683)应该修复它

I don't have the file 'SVGKit.podspec'

**Comment by adamgit** [comment]
> @adamgit Swift Package Manager work best with git tags so a new tag need to be added such as **3.0.0** to allow the use of SVGKit as a swift package.

Traditionally we don't do a version release (With git-tag) without doing a complete suite of manual testing, builds on different OS versions, etc.

If someone wants to step forwards and volunteer to manage and perform that, then great. Otherwise ... it's a lot of effort and personally I don't have the bandwidth for it right now.

Can SPM work with a floating branch? i.e. tie to the 3.x branch directly?

**Comment by satindar** [comment]
@bangjier I pointed to the commit before the SPM changes.

Use this in your Podfile:

`pod 'SVGKit', :git => 'https://github.com/SVGKit/SVGKit.git', :commit => '2a4068f0ea546dcd82f7e4dd9aa9026c0a0a2235'`

Edit: Looks like the fix was merged in so you can just point to 3.x again. Thank you @karimhm and @adamgit !

**Comment by karimhm** [comment]
> > @adamgit Swift Package Manager work best with git tags so a new tag need to be added such as **3.0.0** to allow the use of SVGKit as a swift package.
> 
> Traditionally we don't do a version release (With git-tag) without doing a complete suite of manual testing, builds on different OS versions, etc.
> 
> If someone wants to step forwards and volunteer to manage and perform that, then great. Otherwise ... it's a lot of effort and personally I don't have the bandwidth for it right now.
> 
> Can SPM work with a floating branch? i.e. tie to the 3.x branch directly?

Yes its possible to point to a branch or to a specific commit hash.

**Comment by bangjier** [comment]
> @bangjier I pointed to the commit before the SPM changes.
> 
> Use this in your Podfile:
> 
> `pod 'SVGKit', :git => 'https://github.com/SVGKit/SVGKit.git', :commit => '2a4068f0ea546dcd82f7e4dd9aa9026c0a0a2235'`
> 
> Edit: Looks like the fix was merged in so you can just point to 3.x again. Thank you @karimhm and @adamgit !

Thank you, specify 3.x still does not work, specify commit solved

**Comment by karimhm** [comment]
@bangjier #686 fix this.

**Pull request merged**
