### PR TITLE
Hotfix for CGPathAddRoundedRect compile error on iOS 7.

### PR DESCRIPTION
**Pull request by MartinMReed**
Added iOS version check to use the built-in CGPathAddRoundedRect when compiling for iOS 7. This commit resolves issue #99.

### CODE REVIEW

**Comment by MaddTheSane** [comment]
Is the master branch the one we should be using as a baseline?

**Comment by adamgit** [comment]
Argh, no - sorry, I thought it was against 1.1.0 or I wouldnt have approved
it. My mistake.

**Comment by MartinMReed** [comment]
Why not, it was a hotfix? Master wasn't even usable on iOS7 without it. iOS7 is no longer in beta, which was your original reason for not fixing it.

**Comment by adamgit** [comment]
Sure, and you didnt do anything wrong but i should have spooen to
you. You're possibly making assumptions about the contents of master that
are reasonable but incorrect. I've tried getting evryone to use it the same
way, but too many people dont read instructions, and it became a mess.

I dont blame them. Github has no easy way of saying "development branch is
X, live branch is Y", and trying to use some standard git approaches has
failed because of that, and because different people have incompatible
ideas about what master should point to.

(Whats worked very well on commercial projects, where we all work together
in one team, doesnt work where every contributor is separate)

So ... The plan is to re invent master in a way that will be misinterpreted
by the smallest number of people. Thats non trivial, both working out
"what" and also shuffling branbes to make it true. Until then, we've been
saying its to be avoided, and Ive been pushing people to do all changes
against 1.1.0 branch.

It might make sense to additionally backport something to master, but not
to do it there first.

**Comment by MartinMReed** [comment]
Okay. Under the repo settings you can change the default branch so people will arrive at 1.1.0 instead of master. Having it presented first will probably help funnel new commits into it.

**Comment by adamgit** [comment]
Cool, that would be a big help, thanks

**Pull request merged**
