### PR TITLE
Change CocoaLumberjack to 3.x

### LINKED ISSUE #481: Use of undeclared identifier LOG_LEVEL_DEF
Using latest Xcode I'm getting this error.  Can bypass this if I `#define` them to `0`, but doesn't seem like a long term plan

### PR DESCRIPTION
**Pull request by cpboyd**
Fixes #481 and #500

### CODE REVIEW

**Comment by cpboyd** [comment]
This updates the podspec's CocoaLumberjack to 3.x and corrects the import to work with the Swift Framework (which resulted in #481 starting in CocoaLumberjack 2.4).

**Comment by cpboyd** [comment]
@Streebor 
I don't know if there's a good workaround until https://github.com/CocoaLumberjack/CocoaLumberjack/issues/778 is fixed.

CocoaLumberjack hasn't supported the non-framework `#import <CocoaLumberjack/CocoaLumberjack.h>` since 2.3.

Is there a specific reason you're against using frameworks?

There haven't yet been any commits related to any other issue, so you could possibly specify commit 6a89432 in your podfile for now.
e.g. `pod 'SVGKit', :git => 'https://github.com/SVGKit/SVGKit.git', :commit => '6a89432'`

**Comment by Streebor** [comment]
@cpboyd Thank you for your quick response!

There are other older libraries what we depend on that do not support frameworks. But even bigger problem is our app's extension for Messages. App extensions cannot have frameworks  because the whole app will be rejected.

**Comment by cpboyd** [comment]
@Streebor 
Regarding app extensions (and assuming you're using Cocoapods):
https://github.com/CocoaPods/CocoaPods/issues/4203 and a related merge  https://github.com/CocoaPods/CocoaPods/pull/5732

I don't know if those would apply to a Messages app extension without a host app, though.

There's also https://github.com/CocoaPods/CocoaPods/issues/5594 and  https://github.com/CocoaPods/CocoaPods/issues/5860 which do specify Messages extensions and embedding frameworks.

I'm not really sure I understand what you mean by older libraries not supporting:
Do you mean that they don't work with the newer CocoaLumberjack?

I mean, there's some people like #500 that want/need the newer version.

**Pull request merged**
