### PR TITLE
hack around renderInContext bug

### PR DESCRIPTION
**Pull request by iliaskarim**
`Apparently, they introduced a bug on the renderInContext when the view contains 0 in the width` - https://github.com/nicklockwood/FXBlurView/issues/79 (crashes)

### CODE REVIEW

**Comment by adamgit** [comment]
c.f. #278 comments - the const change is probably wrong.

If you can provide a pull request that ONLY makes the changes you describe - great! I'll merge it.

But currently, this PR contains many other unrelated changes, most of which are not good. e.g. I don't like the change from int to long - should be a change to appropriate NS\* integer if anything, now that apple has redefined all integers.

**Comment by iliaskarim** [comment]
hey @adamgit thanks for your response! I really only meant to draw your attention to the one commit  in question: [3928df9](https://github.com/djz-code/SVGKit/commit/3928df9beb097e7802c74e22f1bc620d99b0e233)

does that one look good to you? If so I'll prepare a pull request

**Comment by adamgit** [comment]
That one looks OK to me.

Greg has been checking in some improvements to the "bounds" generation recently - might not be needed any more?

(I think it is needed, just saying: check with latest)

**Comment by iliaskarim** [comment]
can confirm that the issue seems resolved in 1.2 👍🏻

**Pull request closed without merging**
