### PR TITLE
Fix Demo-OSX build

### PR DESCRIPTION
**Pull request by dtweston**
Even though they look UIKit specific, these header files use macros to also work on macOS

### CODE REVIEW

**Comment by adamgit** [comment]
Good point. I feel we should also rename the containing folder from something other thatn "UIKit Additions".

Is there a good common name that captures the platforms where this is relevant?

**Comment by dtweston** [comment]
Maybe it would be better to just call it "ImageViews"?

**Comment by adamgit** [comment]
Sounds good to me. Can you combine with this and I can put it through in one go?

**Comment by dtweston** [comment]
Done.

**Pull request merged**
