### PR TITLE
Make dealloc happy.

### PR DESCRIPTION
**Pull request by MaddTheSane**

### CODE REVIEW

**Comment by tspecht** [comment]
any chance this is going to be merged?

**Comment by adamgit** [comment]
How does this fix the problem? It appears identical to the code that we know causes randomized crashes in live builds.

I see that you're shifting the addObserver call to go before the "failed to parse, set self=nil" ... is this the cause of the randomized crashes?

(I thought they happened mostly with files that had parsed correctly?)

**Comment by adamgit** [comment]
@scriptedSheep I don't think we have a simple, verified, reliable test case for proving the crash problem, so it's difficult to merge this.

Bear in mind that merging it - if it's not completely successful - will cause existing apps to start hard crashing :(.

**Comment by MaddTheSane** [comment]
I placed the observer addition happens before the first return nil, so the removal of the observer in dealloc doesn't crash the app.

**Comment by tspecht** [comment]
I don't know if this helps you with reproducing the issue, but in my application the exception occured when quickly switching the SVG rendered in  the image view. So I guess a for-loop just setting a new image every time could do the trick?

**Comment by tspecht** [comment]
Any news on this=

**Comment by keepingitneil** [comment]
Hey all, I'm experiencing this same issue. Happens often because I'm creating and removing SVGKImages often (in a tableview). @MaddTheSane , you said you fixed this? Any word over time if the fix holds? Seems to crash when scrolling quickly on the table views. Love SVGKit and appreciate all of the work that went into it but this random crash is really making me consider the webview route :(

**Comment by MaddTheSane** [comment]
I'll try creating a test case, but it'll probably be in another pull request.

**Comment by MaddTheSane** [comment]
The retain tests are now in merge request #227.

**Comment by adamgit** [comment]
Nice tests. Merged.

@keepingitneil - can you try them with your SVG and report back?

**Comment by MaddTheSane** [comment]
These are my test results, ran internally in Xcode 6.1:

Before this patch:

```
Test Suite 'All tests' started at 2014-10-14 18:52:20 +0000
Test Suite 'SVGKit-iOS Tests.xctest' started at 2014-10-14 18:52:20 +0000
Test Suite 'SVGKit_iOS_ARCRetainTests' started at 2014-10-14 18:52:20 +0000
Test Case '-[SVGKit_iOS_ARCRetainTests testReleasing]' started.
Test Case '-[SVGKit_iOS_ARCRetainTests testReleasing]' passed (0.001 seconds).
Test Case '-[SVGKit_iOS_ARCRetainTests testReplacing]' started.
<unknown>:0: error: -[SVGKit_iOS_ARCRetainTests testReplacing] : failed: caught "NSInternalInconsistencyException", "An instance 0x78780320 of class SVGKImage was deallocated while key value observers were still registered with it. Current observation info:  <NSKeyValueObservationInfo 0x790ecb10> (
<NSKeyValueObservance 0x790ecad0: Observer: 0x78780320, Key path: DOMTree.viewport, Options: <New: NO, Old: YES, Prior: NO> Context: 0x0, Property: 0x7877ed20>
)"
(
    0   CoreFoundation                      0x008d7946 __exceptionPreprocess + 182
    1   libobjc.A.dylib                     0x00560a97 objc_exception_throw + 44
    2   CoreFoundation                      0x008d786d +[NSException raise:format:] + 141
    3   Foundation                          0x001916d4 NSKVODeallocate + 379
    4   libobjc.A.dylib                     0x00575772 _ZN11objc_object17sidetable_releaseEb + 248
    5   libobjc.A.dylib                     0x00574e9b objc_release + 43
    6   libobjc.A.dylib                     0x00575d32 _ZN12_GLOBAL__N_119AutoreleasePoolPage3popEPv + 586
    7   XCTest                              0x20108983 -[XCTestCase invokeTest] + 328
    8   XCTest                              0x20108bb9 -[XCTestCase performTest:] + 184
    9   XCTest                              0x20114162 -[XCTest run] + 314
    10  XCTest                              0x20107598 -[XCTestSuite performTest:] + 406
    11  XCTest                              0x20114162 -[XCTest run] + 314
    12  XCTest                              0x20107598 -[XCTestSuite performTest:] + 406
    13  XCTest                              0x20114162 -[XCTest run] + 314
    14  XCTest                              0x20107598 -[XCTestSuite performTest:] + 406
    15  XCTest                              0x20114162 -[XCTest run] + 314
    16  XCTest                              0x20103de2 __25-[XCTestDriver _runSuite]_block_invoke + 61
    17  XCTest                              0x20110c82 -[XCTestObservationCenter _observeTestExecutionForBlock:] + 184
    18  XCTest                              0x20103d06 -[XCTestDriver _runSuite] + 285
    19  XCTest                              0x20104951 -[XCTestDriver _checkForTestManager] + 272
    20  XCTest                              0x20104c6b -[XCTestDriver runTestSuite:completionHandler:] + 378
    21  XCTest                              0x2011775c +[XCTestProbe runTests:] + 216
    22  libobjc.A.dylib                     0x0057667e +[NSObject performSelector:withObject:] + 70
    23  xctest                              0x0009a237 xctest + 4663
    24  xctest                              0x0009a4ac xctest + 5292
    25  xctest                              0x0009a58f xctest + 5519
    26  xctest                              0x00099e3d xctest + 3645
    27  libdyld.dylib                       0x01a56ac9 start + 1
)
Test Case '-[SVGKit_iOS_ARCRetainTests testReplacing]' failed (0.093 seconds).
```

After the patch:

```
Test Suite 'All tests' started at 2014-10-14 18:58:05 +0000
Test Suite 'SVGKit-iOS Tests.xctest' started at 2014-10-14 18:58:05 +0000
Test Suite 'SVGKit_iOS_ARCRetainTests' started at 2014-10-14 18:58:05 +0000
Test Case '-[SVGKit_iOS_ARCRetainTests testReleasing]' started.
Test Case '-[SVGKit_iOS_ARCRetainTests testReleasing]' passed (0.001 seconds).
Test Case '-[SVGKit_iOS_ARCRetainTests testReplacing]' started.
Test Case '-[SVGKit_iOS_ARCRetainTests testReplacing]' passed (0.063 seconds).
Test Case '-[SVGKit_iOS_ARCRetainTests testSameFileTwice]' started.
Test Case '-[SVGKit_iOS_ARCRetainTests testSameFileTwice]' passed (0.000 seconds).
Test Suite 'SVGKit_iOS_ARCRetainTests' passed at 2014-10-14 18:58:05 +0000.
     Executed 3 tests, with 0 failures (0 unexpected) in 0.064 (0.066) seconds
Test Suite 'SVGKit_iOS_RetainTests' started at 2014-10-14 18:58:05 +0000
Test Case '-[SVGKit_iOS_RetainTests testReleasing]' started.
Test Case '-[SVGKit_iOS_RetainTests testReleasing]' passed (0.000 seconds).
Test Case '-[SVGKit_iOS_RetainTests testReplacing]' started.
Test Case '-[SVGKit_iOS_RetainTests testReplacing]' passed (0.044 seconds).
Test Case '-[SVGKit_iOS_RetainTests testSameFileTwice]' started.
Test Case '-[SVGKit_iOS_RetainTests testSameFileTwice]' passed (0.000 seconds).
Test Suite 'SVGKit_iOS_RetainTests' passed at 2014-10-14 18:58:05 +0000.
     Executed 3 tests, with 0 failures (0 unexpected) in 0.045 (0.048) seconds
Test Suite 'SVGKit-iOS Tests.xctest' passed at 2014-10-14 18:58:05 +0000.
     Executed 6 tests, with 0 failures (0 unexpected) in 0.110 (0.116) seconds
Test Suite 'All tests' passed at 2014-10-14 18:58:05 +0000.
     Executed 6 tests, with 0 failures (0 unexpected) in 0.110 (0.118) seconds
Program ended with exit code: 0
```

**Comment by keepingitneil** [comment]
@MaddTheSane With regards to this issue, my project never failed on any one particular SVG (the project has many SVGs being generated elsewhere and being rendered and deallocated many times which would sometimes crash because of KVO stuff. I can confirm that this is no longer happens after this fix.

**Comment by adamgit** [comment]
We have so many competing fixes for this that I can't keep track of them.

Allegegedly 2.x now has this fixed (according to a few reports I've had).

Can either of you confirm current 2.x is now fixed, or - if not - pull, resolve conflicts, re-test this, and then re-submit? I'm sorry this didn't get merged at the time!

**Pull request closed without merging**
